FROM node:18

WORKDIR /home/node/app

ARG APPLICATION_PORT
ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_NAME

RUN test -n "${APPLICATION_PORT}"
RUN test -n "${DB_USERNAME}"
RUN test -n "${DB_PASSWORD}"
RUN test -n "${DB_NAME}"

ENV PORT=${APPLICATION_PORT}
ENV DB_USERNAME=${DB_USERNAME}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_NAME=${DB_NAME}

CMD [ "yarn", "dev:start" ]